In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import random

In [ ]:
# Define the range for each attribute
num_entities = 4000

wallet_numbers = ['1' + ''.join([str(random.randint(0, 9)) for _ in range(9)]) for _ in range(num_entities)]


address_percentages = {
    "Urban": 0.8,
    "Rural": 0.2
}

# Create a list of addresses based on their percentages
addresses = random.choices(list(address_percentages.keys()), k=num_entities, weights=list(address_percentages.values()))


genders = random.choices(["Male", "Female"], k=num_entities)

balances = [round(random.uniform(2000,10000), 2) for _ in range(num_entities)]

balance_deviations = [round(random.uniform(50, 80), 2) for _ in range(num_entities)]

In [ ]:
# Define age ranges for different occupations
age_ranges = {

"Business": (25, 50),
    "Private Service": (20,60),
    "Govt. Service": (20,60),
    "House Wife": (30, 60),
    "Student": (18, 25)


}

In [ ]:
# Define the possible occupations and their respective percentages
occupations = [
     ("Business", 0.25),
    ("House Wife", 0.15),
    ("Student", 0.5),
    ("Private Service",0.05),
    ("Govt. Service",0.05)


]

In [ ]:
# Create lists for occupations and ages based on the defined age ranges
occupation_list = []
age_list = []

for occupation, percentage in occupations:
    occupation_count = int(num_entities * percentage)
    occupation_list.extend([occupation] * occupation_count)
    age_min, age_max = age_ranges[occupation]
    age_list.extend([random.randint(age_min, age_max) for _ in range(occupation_count)])

# Shuffle the occupation and age lists to randomize the assignment
combined = list(zip(occupation_list, age_list))
random.shuffle(combined)
occupation_list, age_list = zip(*combined)

In [ ]:
# Create a DataFrame
data = {
    "Wallet No": wallet_numbers,
    "Address": addresses,
    "Balance": balances,
    "Age": age_list,
    "Occupation": occupation_list,
    "Loan Approval": "Eligible",
    "Balance Deviation (CV)": balance_deviations,

}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

,Wallet No,Address,Balance,Age,Occupation,Loan Approval,Balance Deviation (CV)
0,1701285247,Rural,2204.37,24,Student,Eligible,71.20
1,1182321214,Urban,2213.98,51,Private Service,Eligible,55.77
2,1390132785,Urban,6412.52,20,Student,Eligible,57.81
3,1960895891,Urban,7388.06,37,Business,Eligible,72.48
4,1633813882,Urban,3844.91,31,Private Service,Eligible,55.85
...,...,...,...,...,...,...,...
3995,1808468568,Urban,7009.52,21,Student,Eligible,50.08
3996,1296565174,Urban,7714.78,23,Student,Eligible,73.35
3997,1218498173,Urban,9135.19,36,House Wife,Eligible,66.18
3998,1812676406,Urban,9807.37,22,Student,Eligible,73.47
3999,1574400178,Urban,7378.83,46,Business,Eligible,73.21

In [ ]:
# Define integer columns with specified ranges
integer_columns = {
    "Send Money_1": (2,5),
    "Send Money_2": (8,15),
    "Send Money_3": (0,2),
    "Received Money_1": (5,10),
    "Received Money_2": (12,20),
    "Received Money_3": (0,1),
    "Cash In_1": (2,4),
    "Cash In_2" : (8,10),
    "Cash In_3" : (0,2),
    "Cash Out_1" : (2,5),
    "Cash Out_2" : (5,12),
"Cash Out_3": (0,1),
"Make Payment_1": (0,2),
"Make Payment_2": (1,3),
"Make Payment_3" : (0,1),
"Pay Bill_1": (0,5),
"Pay Bill_2" : (0,1),
"Add Money_1": (3,5),
"Add Money_2": (6,12),
"Add Money_3": (0, 1),
"Fund Transfer_1" : (0, 2),
"Fund Transfer_2" : (0, 3),
"Fund Transfer_3" : (0,1),
"Request Money" : (0,4),
"Others_1" : (0, 2),
"Others_2" : (0, 2),
"Others_3" : (0, 0),
"Donation_1": (0, 3),
"Donation_2" : (0,2),
"Remittance_1": (0,2),
"Remittance_2" : (0,5),
}

for column, (min_val, max_val) in integer_columns.items():
    df[column] = [random.randint(min_val, max_val) for _ in range(num_entities)]

In [ ]:
df

,Wallet No,Address,Balance,Age,Occupation,Loan Approval,Balance Deviation (CV),Send Money_1,Send Money_2,Send Money_3,...,Fund Transfer_2,Fund Transfer_3,Request Money,Others_1,Others_2,Others_3,Donation_1,Donation_2,Remittance_1,Remittance_2
0,1701285247,Rural,2204.37,24,Student,Eligible,71.20,5,12,2,...,0,1,3,2,1,0,3,2,2,4
1,1182321214,Urban,2213.98,51,Private Service,Eligible,55.77,3,8,0,...,2,0,3,1,2,0,2,1,0,2
2,1390132785,Urban,6412.52,20,Student,Eligible,57.81,3,12,1,...,1,1,4,2,0,0,0,1,1,5
3,1960895891,Urban,7388.06,37,Business,Eligible,72.48,5,8,1,...,3,1,0,1,2,0,3,2,0,2
4,1633813882,Urban,3844.91,31,Private Service,Eligible,55.85,2,13,0,...,3,1,4,2,0,0,3,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,1808468568,Urban,7009.52,21,Student,Eligible,50.08,2,14,2,...,1,1,0,1,0,0,1,2,0,3
3996,1296565174,Urban,7714.78,23,Student,Eligible,73.35,3,12,0,...,3,1,3,0,1,0,3,0,1,5
3997,1218498173,Urban,9135.19,36,House Wife,Eligible,66.18,4,8,1,...,3,0,4,1,2,0,2,2,0,3
3998,1812676406,Urban,9807.37,22,Student,Eligible,73.47,5,15,0,...,1,0,0,2,1,0,0,2,2,5
3999,1574400178,Urban,7378.83,46,Business,Eligible,73.21,5,9,1,...,3,0,4,1,2,0,2,0,2,2

In [ ]:
df.to_csv('/content/drive/MyDrive/Upay/New_df.csv', mode='a', header= False, index = False)

In [ ]:
test_df = pd.read_csv('/content/drive/MyDrive/Upay/New_df.csv')

In [ ]:
test_df

,Wallet No,Address,Balance,Age,Occupation,Loan Approval,Balance Deviation (CV),Send Money_1,Send Money_2,Send Money_3,...,Fund Transfer_2,Fund Transfer_3,Request Money,Remittance_1,Remittance_2,Donation_1,Donation_2,Others_1,Others_2,Others_3
0,1712345678,Urban,29300.00,29,Business,Eligible,32.051120,9,0,0,...,3,0,4,0,0,4,0,1,0,0
1,1887654321,Rural,100.00,35,Student,UC,63.098873,4,0,1,...,0,0,7,1,0,1,0,0,0,0
2,1913579246,Urban,38250.00,38,Business,Eligible,39.525087,1,8,4,...,7,4,0,0,0,8,0,0,0,2
3,1624681012,Urban,57547.30,39,Doctor,Eligible,47.554104,0,3,6,...,0,0,0,0,1,0,0,0,0,2
4,1597531864,Urban,2475.19,24,Student,Eligible,41.175715,0,10,0,...,0,0,2,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36008,1808468568,Urban,7009.52,21,Student,Eligible,50.080000,2,14,2,...,1,1,0,1,0,0,1,2,0,3
36009,1296565174,Urban,7714.78,23,Student,Eligible,73.350000,3,12,0,...,3,1,3,0,1,0,3,0,1,5
36010,1218498173,Urban,9135.19,36,House Wife,Eligible,66.180000,4,8,1,...,3,0,4,1,2,0,2,2,0,3
36011,1812676406,Urban,9807.37,22,Student,Eligible,73.470000,5,15,0,...,1,0,0,2,1,0,0,2,2,5
36012,1574400178,Urban,7378.83,46,Business,Eligible,73.210000,5,9,1,...,3,0,4,1,2,0,2,0,2,2

In [ ]:
test_df.to_csv('/content/drive/MyDrive/Upay/Final.csv', index = False)